# -*- coding: utf-8 -*-
"""SARIMA_ARWipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcmI_VGITUd6iW-R0i8pPQmLyorCD-Qz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import adfuller

"""### Import Data

"""

import pandas as pd

# Read the XLSX file to inspect actual column names
temp_df = pd.read_excel('data dibalik fix.xlsx')

temp_df.head()

"""Splitting Data"""

import pandas as pd

# Assuming temp_df is already loaded and sorted by 'Tanggal'
# If not, ensure it's sorted:
# temp_df = temp_df.sort_values(by='Tanggal').reset_index(drop=True)

# Determine the split point (e.g., 80% for training, 20% for testing)
split_ratio = 0.8
split_index = int(len(temp_df) * split_ratio)

# Split the data into training and testing sets
train_data = temp_df.iloc[:split_index]
test_data = temp_df.iloc[split_index:]

print(f"Training set size: {len(train_data)} records")
print(f"Testing set size: {len(test_data)} records")

print("\nHead of Training Data:")
display(train_data.head())

print("\nHead of Testing Data:")
display(test_data.head())

"""# Train data"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(train_data['Tanggal'], train_data['Konsumsi'])
plt.title('Time Series of Konsumsi (Training Data)')
plt.xlabel('Tanggal')
plt.ylabel('Konsumsi')
plt.grid(True)
plt.tight_layout()
plt.show()

"""ACF dan PACF"""

import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# ACF for training data
plt.figure(figsize=(12, 8))
plot_acf(train_data['Konsumsi'], lags=40, ax=plt.gca(), zero=False)
plt.title('ACF — Konsumsi (Training Data)')
plt.show()

# PACF for training data
plt.figure(figsize=(12, 8))
plot_pacf(train_data['Konsumsi'], lags=40, ax=plt.gca(), zero=False, method='ywm')
plt.title('PACF — Konsumsi (Training Data)')
plt.show()

"""### Transformmasi"""

import numpy as np

# Logarithmic Transformation on training data
train_data_log = np.log(train_data['Konsumsi'])

# First-order differencing on training data
train_data_diff = train_data['Konsumsi'].diff().dropna()

# Log then differencing on training data
train_data_log_diff = np.log(train_data['Konsumsi']).diff().dropna()

print("Original Training Konsumsi Series Head:\n", train_data['Konsumsi'].head())
print("\nLog Transformed Training Konsumsi Series Head:\n", train_data_log.head())
print("\nFirst Differenced Training Konsumsi Series Head:\n", train_data_diff.head())
print("\nLog then Differenced Training Konsumsi Series Head:\n", train_data_log_diff.head())

"""Plot TS after Traansformasi"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))
plt.plot(train_data_log)
plt.title('Training Data — Log Transformed Konsumsi')
plt.xlabel('Date'); plt.ylabel('Log(Konsumsi)'); plt.tight_layout(); plt.show()

plt.figure(figsize=(10, 4))
plt.plot(train_data_diff)
plt.title('Training Data — First Differenced Konsumsi')
plt.xlabel('Date'); plt.ylabel('Differenced Konsumsi'); plt.tight_layout(); plt.show()

plt.figure(figsize=(10, 4))
plt.plot(train_data_log_diff)
plt.title('Training Data — Log then Differenced Konsumsi')
plt.xlabel('Date'); plt.ylabel('Log-Differenced Konsumsi'); plt.tight_layout(); plt.show()

"""### Differencing 1

"""

import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# The first-order differenced series for training data (train_data_diff) has already been computed.

plt.figure(figsize=(10,4))
plt.plot(train_data_diff)
plt.title('First-differenced Konsumsi Series (Training Data)')
plt.xlabel('Index'); plt.ylabel('Differenced Konsumsi'); plt.tight_layout(); plt.show()

# ADF test for stationarity on the first-differenced training data
res_train_diff1 = adfuller(train_data_diff)
print('ADF stat (first-differenced train data):', res_train_diff1[0], 'p-value:', res_train_diff1[1])
if res_train_diff1[1] > 0.05:
    print('First-differenced training data is likely non-stationary (p-value > 0.05).')
else:
    print('First-differenced training data is likely stationary (p-value <= 0.05).')

# ACF and PACF plots for the first-differenced training series
plt.figure(figsize=(12, 8))
plot_acf(train_data_diff, lags=40, ax=plt.gca(), zero=False)
plt.title('ACF — First-differenced Konsumsi (Training Data)')
plt.show()

plt.figure(figsize=(12, 8))
plot_pacf(train_data_diff, lags=40, ax=plt.gca(), zero=False, method='ywm')
plt.title('PACF — First-differenced Konsumsi (Training Data)')
plt.show()

"""### Seasonal Diff Train"""

import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Apply seasonal differencing (lag 12) to the already first-differenced training series
train_data_diff_seasonal_diff = train_data_diff.diff(periods=12).dropna()

plt.figure(figsize=(10,4))
plt.plot(train_data_diff_seasonal_diff)
plt.title('First-Differenced then Seasonally Differenced Konsumsi (Training Data, Lag 12)')
plt.xlabel('Index'); plt.ylabel('Diff-Seasonal Diff Konsumsi'); plt.tight_layout(); plt.show()

# ADF test for stationarity on the combined differenced training data
res_train_diff_seasonal_diff = adfuller(train_data_diff_seasonal_diff)
print('ADF stat (diff then seasonal diff train data):', res_train_diff_seasonal_diff[0], 'p-value:', res_train_diff_seasonal_diff[1])
if res_train_diff_seasonal_diff[1] > 0.05:
    print('Combined differenced training data is likely non-stationary (p-value > 0.05).')
else:
    print('Combined differenced training data is likely stationary (p-value <= 0.05).')

# ACF and PACF plots for the combined differenced training series
plt.figure(figsize=(12, 8))
plot_acf(train_data_diff_seasonal_diff, lags=40, ax=plt.gca(), zero=False)
plt.title('ACF — First-Differenced then Seasonally Differenced Konsumsi (Training Data)')
plt.show()

plt.figure(figsize=(12, 8))
plot_pacf(train_data_diff_seasonal_diff, lags=40, ax=plt.gca(), zero=False, method='ywm')
plt.title('PACF — First-Differenced then Seasonally Differenced Konsumsi (Training Data)')
plt.show()